import 'ember-mobile-menu/themes/android';
/**
 * NOTE: while this project uses tailwind,
 *   CSS is better than tailwind for
 *   - global styles
 *   - styling some recursive structures generated by other libraries.
 *
 * Using both together is *very nice* 🎉
 */
import './site-css/site.css';
import './site-css/components.css';
import './site-css/featured-demo.css';
import './site-css/shiki.css';
import './site-css/shell.css';
import type { TOC } from '@ember/component/template-only';
export declare const Shell: TOC<{
    Blocks: {
        default: [];
    };
}>;
//# sourceMappingURL=shell.gts.d.ts.map