name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      pending: ${{ steps.set-pending.outputs.pending }}
    steps:
      - uses: wyvox/action@v1
      - run: pnpm build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 5
    steps:
      - uses: wyvox/action@v1
      - run: pnpm build
      - run: pnpm lint


  test:
    name: "Default Tests"
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 5
    steps:
      - uses: wyvox/action@v1
      - run: pnpm build
      - run: pnpm test 

  # try-scenarios:
  #   name: ${{ matrix.try-scenario }}
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   timeout-minutes: 10
  #   # if: ${{ fromJSON(needs.setup.outputs.pending).test-app.test.status == 'MISS' }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       try-scenario:
  #         - ember-lts-4.12
  #         - ember-5.1
  #         - ember-release
  #         - ember-beta
  #         - ember-canary
  #
  #   steps:
  #     - uses: wyvox/action@v1
  #       with:
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
  #         node-version: 18.18.1
  #     - run: pnpm build
  #     - name: Run Tests
  #       run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }} --skip-cleanup
  #       working-directory: test-app
